.\"  Copyright (c) 2020 Mark J. Olesen
.\"
.\"  CC BY 4.0
.\"
.\"  This file is licensed under the Creative Commons Attribution 4.0 
.\"  International license.
.\"
.\"  You are free to:
.\"
.\"    Share --- copy and redistribute the material in any medium or format
.\" 
.\"    Adapt --- remix, transform, and build upon the material for any purpose,
.\"              even commercially
.\"
.\"  Under the following terms:
.\"
.\"    Attribution --- You must give appropriate credit, provide a link
.\"                    to the license, and indicate if changes were made. You
.\"                    may do so in any reasonable manner, but not in any way
.\"                    that suggests the licensor endorses you or your use.
.\"
.\"   Full text of this license can be found in 
.\"   '${MJO_HOME}/licenses/CC-BY-SA-4.0'or visit 
.\"   'http://creativecommons.org/licenses/by/4.0/' or send a letter 
.\"   to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
.\"
.\"  This file is part of mjo library
.\"
.Dd July 22, 2020
.Os
.Dt msysstat.h 7
.Sh NAME
.Nm msysstat.h
.Nd file status flags
.Sh LIBRARY
.Lb libmjo
.Sh SYNOPSIS
.In msysstat.h
.Fd #define S_IRUSR
.Fd #define S_IWUSR
.Fd #define S_IXUSR
.Fd #define S_IRGRP
.Fd #define S_IWGRP
.Fd #define S_IXGRP
.Fd #define S_IROTH
.Fd #define S_IWOTH
.Fd #define S_IXOTH
.Fd #define S_IRWXU
.Fd #define S_IRWXG
.Fd #define S_IRWXO
.Fd #define stat
.Fd #define fstat
.Sh INCLUDES
.D1 In sys/stat.h
.Sh DESCRIPTION
Provides stat and fstat routines along with file status flags on platforms
that does not implement them.
